from .qrcode import (
    VCardQRCodeViewSet,
    WifiQRCodeViewSet,
    TikTokQRCodeViewSet,
    TelegramQRCodeViewSet,
    InstagramQRCodeViewSet,
    SnapchatQRCodeViewSet,
    SkypeQRCodeViewSet,
    WhatsAppQRCodeViewSet,
    FacebookQRCodeViewSet,
    EPCQRCodeViewSet,
    MediaUrlViewSet,
    LinkedInQRCodeViewSet,
    BitcoinQRCodeViewSet,
    BarcodeTextViewSet,
    BarcodeUrlViewSet,
)

__all__ = [
    "VCardQRCodeViewSet",
    "WifiQRCodeViewSet",
    "TikTokQRCodeViewSet",
    "TelegramQRCodeViewSet",
    "InstagramQRCodeViewSet",
    "SnapchatQRCodeViewSet",
    "SkypeQRCodeViewSet",
    "WhatsAppQRCodeViewSet",
    "FacebookQRCodeViewSet",
    "EPCQRCodeViewSet",
    "MediaUrlViewSet",
    "LinkedInQRCodeViewSet",
    "BitcoinQRCodeViewSet",
    "BarcodeTextViewSet",
    "BarcodeUrlViewSet",
]
